### ISSUE TITLE
how can i found folder AA

### ISSUE THREAD

**Issue by hanicsgo** [Stewart-Anubis/Zr-Breakable-Boss-HUD#4]
How can i see folder materials/overlays/AA/..... vmt

**Comment by Stewart-Anubis** [comment]
This specific folder is just an example.
You have to add in "installation/materials/overlays/belialg/hitmarkers folder", the files are in the repository. And they are directed in sm_boss_hud_hitmarker_vmt "overlays/belialg/hitmarkers/hitmarker0.vmt" and sm_boss_hud_zombie_hitmarker_vmt "overlays/belialg/hitmarkers/hitmarker0.vmt" in "installation folder/cfg/sourcemod/Boss_hud.cfg".

**Comment by hanicsgo** [comment]
thanks u
