### ISSUE TITLE
Hello I tried This PLugins And it worked on my Zombie escape Server but we need more maps

### ISSUE THREAD

**Issue by Meguzio** [Stewart-Anubis/Zr-Breakable-Boss-HUD#5]
Maps/materials/sounds/ Please Help with this 2 maps 
COUNTDOWN FOR MAPS LIKE : ze_aot_trost_v6 ,ze_pirates_port_royal_v5_6
FOR EXAMPLE: >>> GATES WILL BE OPEN ON 20 SEONCDS<<<
CONFIGS /materials are missing for this 2 maps and ofc COUNTDOWN is missing Zombie Escape Mod

**Comment by Stewart-Anubis** [comment]
"Boss_Hud" does not automatically create files, and does not depend on "Models/Materilas/", only custom crosshair files. Boss_hud is compatible with the gfclan configuration files "https://github.com/gflclan-cs-go-ze/ZE-Configs/tree/master/bosshud". If you need to create a file for a specific map use "https://github.com/gflclan-cs-go-ze/bhud-debugger" to watch entities and events to create the file "manually".
